// Code generated by internal/generate/clientconfig/main.go; DO NOT EDIT.
package conns

import (
	"github.com/aws/aws-sdk-go/aws/session"
)

func (c *Config) clientConns(sess *session.Session) *AWSClient {
	return &AWSClient{}
}
